# go语言使用Viper读取配置文件
[tool]
[tool.commitizen]
name = "cz_conventional_commits"
version = "0.0.0"
tag_format = "$version"
use_shortcuts = true
update_changelog_on_bump = true
annotated_tag = true

[myproject]
listening_host = "0.0.0.0"
listening_port = 8008