basePath: /api/trsframe
definitions:
  index.HomeResp:
    properties:
      message:
        description: 验活接口响应消息
        example: success
        type: string
    type: object
host: localhost:22887
info:
  contact: {}
  description: TrsFrame RESTful API
  title: TrsFrame
  version: 1.0.0
paths:
  /:
    get:
      consumes:
      - application/json
      description: 验活接口
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/index.HomeResp'
        "400":
          description: Bad Request
      summary: index
      tags:
      - index
schemes:
- http
- https
swagger: "2.0"
